### ISSUE TITLE
Device detection

### ISSUE THREAD

**Issue by UselessGuru** [hidden-69/NanoMinerService#1]
Not sure why you want to run it a service.

If you want device detection in pwsh look here:
https://github.com/Minerx117/NemosMiner/blob/testing/Data/Devices.json
https://github.com/Minerx117/NemosMiner/tree/testing/Includes/OpenCL
https://github.com/Minerx117/NemosMiner/blob/c90ba5741b2a853b7474accdf9cb953f9b5ba373/NemosMiner.ps1#L267
https://github.com/Minerx117/NemosMiner/blob/c90ba5741b2a853b7474accdf9cb953f9b5ba373/Includes/Include.psm1#L1852

**Comment by hidden-69** [comment]
Because it would auto-start after a reboot without a logged in user.
